# QUESTIONS
1. Create an empty dictionary and fill with some sub_code and sub_name as pair by user
input. Then take one sub_code as input from the user and traverse through dictionary
to find the corresponding sub_name and display the same.
2. Create an empty list and fill with list of words by user input. Find the list of words that
are longer than n from a given list of words.
Sample List : [‘the’,’quick’,’brown’,’fox’]
n : 3
Expected Result : quick brown
3. Create an empty set and fill with some values by user input. Check if a given value is
present in a set or not.
4. Create an empty tuple and fill with some values by user input. Count the occurrence of
a given input number in the tuple.
Sample : (50, 10, 60, 70, 50)
n : 50
Expected Result : 2
5. Create a 2D array and perform matrix subtraction using numpy.
6. Read an .csv file and display the basic details.

*1. Create an empty dictionary and fill with some sub_code and sub_name as pair by user
input. Then take one sub_code as input from the user and traverse through dictionary
to find the corresponding sub_name and display the same*

In [6]:
sample_dict = {}
sample_dict['201']="English"
sample_dict['202']="Hindi"
sample_dict['203']="Math"
sample_dict['404']="Data Science"
sample_dict['204']="Science"

CODE_TO_FIND = '204'

for x in sample_dict:
    if x == CODE_TO_FIND:
        print(f"{CODE_TO_FIND} belongs to {sample_dict[CODE_TO_FIND]}")


204 belongs to Science


2. Create an empty list and fill with list of words by user input. <br> Find the list of words that
are longer than n from a given list of words.<br>
Sample List : [‘the’,’quick’,’brown’,’fox’] <br>
n : 3 <br>
Expected Result : quick brown <br>

In [8]:
Sample_List = ['the','quick','brown','fox']
n = 3 
for x in Sample_List:
    if len(x) > n:
        print(x,end=" ")

quick brown 

3. Create an empty set and fill with some values by user input. Check if a given value is
present in a set or not.

In [14]:
temp_set = set()
times = int(input("How many values do you want to add: "))
for x in range(times):
    val = input("enter value"+str(x+1)+" :")
    temp_set.add(val)
VAL_TO_FIND = 2
if str(VAL_TO_FIND) in temp_set:
    print(f"Found {VAL_TO_FIND}")

Found 2


4. Create an empty tuple and fill with some values by user input.<br> Count the occurrence of
a given input number in the tuple.<br>
Sample : (50, 10, 60, 70, 50)<br>
n : 50<br>
Expected Result : 2<br>

In [30]:
temp_tupple = ()
temp = list(temp_tupple)
times = int(input("How many values do you want to add: "))
for x in range(times):
    val = int(input("enter value"+str(x+1)+" :"))
    temp.append(val)
temp_tupple = tuple(temp)
print(temp_tupple)
VAL_TO_FIND_T = 50
if VAL_TO_FIND_T in temp_tupple:
    print(temp_tupple.count(VAL_TO_FIND_T))

(1, 2, 50, 50, 4)
2


In [27]:
test = (1,2,3,4,5,1)
print(test.count(1))

2


5. Create a 2D array and perform matrix subtraction using numpy.

In [23]:
import numpy as np
matrix_1 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,5]])
matrix_2 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(matrix_1-matrix_2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 1]]


6. Read an .csv file and display the basic details.

In [25]:
import pandas as pd
df = pd.read_csv("Datasets/Heart.csv")
print(df)

     Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope  Ca        Thal  AHD  
0        0   